# Generated by Django 5.1.4 on 2024-12-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
