# Generated by Django 5.1.4 on 2024-12-26 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_alter_expense_date_added_alter_income_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
